// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/wrappers.proto

// Protobuf Java Version: 3.25.4
package com.google.protobuf;

public interface BytesValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.BytesValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
