// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/java_features.proto
// Protobuf Java Version: 4.32.1

package com.google.protobuf;

@com.google.protobuf.Generated
public final class JavaFeaturesProto extends com.google.protobuf.GeneratedFile {
  private JavaFeaturesProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      JavaFeaturesProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.protobuf.JavaFeaturesProto.java_);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JavaFeaturesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.JavaFeatures)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the legacyClosedEnum field is set.
     */
    boolean hasLegacyClosedEnum();
    /**
     * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The legacyClosedEnum.
     */
    boolean getLegacyClosedEnum();

    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the utf8Validation field is set.
     */
    boolean hasUtf8Validation();
    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The utf8Validation.
     */
    com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation getUtf8Validation();

    /**
     * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the largeEnum field is set.
     */
    boolean hasLargeEnum();
    /**
     * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The largeEnum.
     */
    boolean getLargeEnum();

    /**
     * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the useOldOuterClassnameDefault field is set.
     */
    boolean hasUseOldOuterClassnameDefault();
    /**
     * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The useOldOuterClassnameDefault.
     */
    boolean getUseOldOuterClassnameDefault();

    /**
     * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
     * @return Whether the nestInFileClass field is set.
     */
    boolean hasNestInFileClass();
    /**
     * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
     * @return The nestInFileClass.
     */
    com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass getNestInFileClass();
  }
  /**
   * Protobuf type {@code pb.JavaFeatures}
   */
  public static final class JavaFeatures extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pb.JavaFeatures)
      JavaFeaturesOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        JavaFeatures.class.getName());
    }
    // Use JavaFeatures.newBuilder() to construct.
    private JavaFeatures(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JavaFeatures() {
      utf8Validation_ = 0;
      nestInFileClass_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.JavaFeaturesProto.JavaFeatures.class, com.google.protobuf.JavaFeaturesProto.JavaFeatures.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.JavaFeatures.Utf8Validation}
     */
    public enum Utf8Validation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UTF8_VALIDATION_UNKNOWN = 0;</code>
       */
      UTF8_VALIDATION_UNKNOWN(0),
      /**
       * <code>DEFAULT = 1;</code>
       */
      DEFAULT(1),
      /**
       * <code>VERIFY = 2;</code>
       */
      VERIFY(2),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 32,
          /* patch= */ 1,
          /* suffix= */ "",
          Utf8Validation.class.getName());
      }
      /**
       * <code>UTF8_VALIDATION_UNKNOWN = 0;</code>
       */
      public static final int UTF8_VALIDATION_UNKNOWN_VALUE = 0;
      /**
       * <code>DEFAULT = 1;</code>
       */
      public static final int DEFAULT_VALUE = 1;
      /**
       * <code>VERIFY = 2;</code>
       */
      public static final int VERIFY_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Utf8Validation valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Utf8Validation forNumber(int value) {
        switch (value) {
          case 0: return UTF8_VALIDATION_UNKNOWN;
          case 1: return DEFAULT;
          case 2: return VERIFY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Utf8Validation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Utf8Validation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Utf8Validation>() {
              public Utf8Validation findValueByNumber(int number) {
                return Utf8Validation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDescriptor().getEnumTypes().get(0);
      }

      private static final Utf8Validation[] VALUES = values();

      public static Utf8Validation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Utf8Validation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.JavaFeatures.Utf8Validation)
    }

    public interface NestInFileClassFeatureOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pb.JavaFeatures.NestInFileClassFeature)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code pb.JavaFeatures.NestInFileClassFeature}
     */
    public static final class NestInFileClassFeature extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:pb.JavaFeatures.NestInFileClassFeature)
        NestInFileClassFeatureOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 32,
          /* patch= */ 1,
          /* suffix= */ "",
          NestInFileClassFeature.class.getName());
      }
      // Use NestInFileClassFeature.newBuilder() to construct.
      private NestInFileClassFeature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private NestInFileClassFeature() {
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_NestInFileClassFeature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_NestInFileClassFeature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.class, com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.Builder.class);
      }

      /**
       * Protobuf enum {@code pb.JavaFeatures.NestInFileClassFeature.NestInFileClass}
       */
      public enum NestInFileClass
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>NEST_IN_FILE_CLASS_UNKNOWN = 0;</code>
         */
        NEST_IN_FILE_CLASS_UNKNOWN(0),
        /**
         * <code>NO = 1;</code>
         */
        NO(1),
        /**
         * <code>YES = 2;</code>
         */
        YES(2),
        /**
         * <code>LEGACY = 3 [feature_support = { ... }</code>
         */
        LEGACY(3),
        ;

        static {
          com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */ 4,
            /* minor= */ 32,
            /* patch= */ 1,
            /* suffix= */ "",
            NestInFileClass.class.getName());
        }
        /**
         * <code>NEST_IN_FILE_CLASS_UNKNOWN = 0;</code>
         */
        public static final int NEST_IN_FILE_CLASS_UNKNOWN_VALUE = 0;
        /**
         * <code>NO = 1;</code>
         */
        public static final int NO_VALUE = 1;
        /**
         * <code>YES = 2;</code>
         */
        public static final int YES_VALUE = 2;
        /**
         * <code>LEGACY = 3 [feature_support = { ... }</code>
         */
        public static final int LEGACY_VALUE = 3;


        public final int getNumber() {
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static NestInFileClass valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static NestInFileClass forNumber(int value) {
          switch (value) {
            case 0: return NEST_IN_FILE_CLASS_UNKNOWN;
            case 1: return NO;
            case 2: return YES;
            case 3: return LEGACY;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<NestInFileClass>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            NestInFileClass> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<NestInFileClass>() {
                public NestInFileClass findValueByNumber(int number) {
                  return NestInFileClass.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.getDescriptor().getEnumTypes().get(0);
        }

        private static final NestInFileClass[] VALUES = values();

        public static NestInFileClass valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private NestInFileClass(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:pb.JavaFeatures.NestInFileClassFeature.NestInFileClass)
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getUnknownFields().writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature)) {
          return super.equals(obj);
        }
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature other = (com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature) obj;

        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pb.JavaFeatures.NestInFileClassFeature}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pb.JavaFeatures.NestInFileClassFeature)
          com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeatureOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_NestInFileClassFeature_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_NestInFileClassFeature_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.class, com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.Builder.class);
        }

        // Construct using com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        public Builder clear() {
          super.clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_NestInFileClassFeature_descriptor;
        }

        public com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature getDefaultInstanceForType() {
          return com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.getDefaultInstance();
        }

        public com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature build() {
          com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature buildPartial() {
          com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature result = new com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature) {
            return mergeFrom((com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature other) {
          if (other == com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }

        // @@protoc_insertion_point(builder_scope:pb.JavaFeatures.NestInFileClassFeature)
      }

      // @@protoc_insertion_point(class_scope:pb.JavaFeatures.NestInFileClassFeature)
      private static final com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature();
      }

      public static com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<NestInFileClassFeature>
          PARSER = new com.google.protobuf.AbstractParser<NestInFileClassFeature>() {
        public NestInFileClassFeature parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<NestInFileClassFeature> parser() {
        return PARSER;
      }

      public com.google.protobuf.Parser<NestInFileClassFeature> getParserForType() {
        return PARSER;
      }

      public com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int LEGACY_CLOSED_ENUM_FIELD_NUMBER = 1;
    private boolean legacyClosedEnum_ = false;
    /**
     * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the legacyClosedEnum field is set.
     */
    public boolean hasLegacyClosedEnum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The legacyClosedEnum.
     */
    public boolean getLegacyClosedEnum() {
      return legacyClosedEnum_;
    }

    public static final int UTF8_VALIDATION_FIELD_NUMBER = 2;
    private int utf8Validation_ = 0;
    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the utf8Validation field is set.
     */
    public boolean hasUtf8Validation() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The utf8Validation.
     */
    public com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation getUtf8Validation() {
      com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation result = com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.forNumber(utf8Validation_);
      return result == null ? com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.UTF8_VALIDATION_UNKNOWN : result;
    }

    public static final int LARGE_ENUM_FIELD_NUMBER = 3;
    private boolean largeEnum_ = false;
    /**
     * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the largeEnum field is set.
     */
    public boolean hasLargeEnum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The largeEnum.
     */
    public boolean getLargeEnum() {
      return largeEnum_;
    }

    public static final int USE_OLD_OUTER_CLASSNAME_DEFAULT_FIELD_NUMBER = 4;
    private boolean useOldOuterClassnameDefault_ = false;
    /**
     * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return Whether the useOldOuterClassnameDefault field is set.
     */
    public boolean hasUseOldOuterClassnameDefault() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
     * @return The useOldOuterClassnameDefault.
     */
    public boolean getUseOldOuterClassnameDefault() {
      return useOldOuterClassnameDefault_;
    }

    public static final int NEST_IN_FILE_CLASS_FIELD_NUMBER = 5;
    private int nestInFileClass_ = 0;
    /**
     * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
     * @return Whether the nestInFileClass field is set.
     */
    public boolean hasNestInFileClass() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
     * @return The nestInFileClass.
     */
    public com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass getNestInFileClass() {
      com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass result = com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass.forNumber(nestInFileClass_);
      return result == null ? com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass.NEST_IN_FILE_CLASS_UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, legacyClosedEnum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, utf8Validation_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, largeEnum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, useOldOuterClassnameDefault_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, nestInFileClass_);
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, legacyClosedEnum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, utf8Validation_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, largeEnum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, useOldOuterClassnameDefault_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, nestInFileClass_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.JavaFeaturesProto.JavaFeatures)) {
        return super.equals(obj);
      }
      com.google.protobuf.JavaFeaturesProto.JavaFeatures other = (com.google.protobuf.JavaFeaturesProto.JavaFeatures) obj;

      if (hasLegacyClosedEnum() != other.hasLegacyClosedEnum()) return false;
      if (hasLegacyClosedEnum()) {
        if (getLegacyClosedEnum()
            != other.getLegacyClosedEnum()) return false;
      }
      if (hasUtf8Validation() != other.hasUtf8Validation()) return false;
      if (hasUtf8Validation()) {
        if (utf8Validation_ != other.utf8Validation_) return false;
      }
      if (hasLargeEnum() != other.hasLargeEnum()) return false;
      if (hasLargeEnum()) {
        if (getLargeEnum()
            != other.getLargeEnum()) return false;
      }
      if (hasUseOldOuterClassnameDefault() != other.hasUseOldOuterClassnameDefault()) return false;
      if (hasUseOldOuterClassnameDefault()) {
        if (getUseOldOuterClassnameDefault()
            != other.getUseOldOuterClassnameDefault()) return false;
      }
      if (hasNestInFileClass() != other.hasNestInFileClass()) return false;
      if (hasNestInFileClass()) {
        if (nestInFileClass_ != other.nestInFileClass_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLegacyClosedEnum()) {
        hash = (37 * hash) + LEGACY_CLOSED_ENUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLegacyClosedEnum());
      }
      if (hasUtf8Validation()) {
        hash = (37 * hash) + UTF8_VALIDATION_FIELD_NUMBER;
        hash = (53 * hash) + utf8Validation_;
      }
      if (hasLargeEnum()) {
        hash = (37 * hash) + LARGE_ENUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLargeEnum());
      }
      if (hasUseOldOuterClassnameDefault()) {
        hash = (37 * hash) + USE_OLD_OUTER_CLASSNAME_DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUseOldOuterClassnameDefault());
      }
      if (hasNestInFileClass()) {
        hash = (37 * hash) + NEST_IN_FILE_CLASS_FIELD_NUMBER;
        hash = (53 * hash) + nestInFileClass_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.JavaFeaturesProto.JavaFeatures prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.JavaFeatures}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.JavaFeatures)
        com.google.protobuf.JavaFeaturesProto.JavaFeaturesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.JavaFeaturesProto.JavaFeatures.class, com.google.protobuf.JavaFeaturesProto.JavaFeatures.Builder.class);
      }

      // Construct using com.google.protobuf.JavaFeaturesProto.JavaFeatures.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        legacyClosedEnum_ = false;
        utf8Validation_ = 0;
        largeEnum_ = false;
        useOldOuterClassnameDefault_ = false;
        nestInFileClass_ = 0;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.JavaFeaturesProto.internal_static_pb_JavaFeatures_descriptor;
      }

      public com.google.protobuf.JavaFeaturesProto.JavaFeatures getDefaultInstanceForType() {
        return com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDefaultInstance();
      }

      public com.google.protobuf.JavaFeaturesProto.JavaFeatures build() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.JavaFeaturesProto.JavaFeatures buildPartial() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures result = new com.google.protobuf.JavaFeaturesProto.JavaFeatures(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.protobuf.JavaFeaturesProto.JavaFeatures result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.legacyClosedEnum_ = legacyClosedEnum_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.utf8Validation_ = utf8Validation_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.largeEnum_ = largeEnum_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.useOldOuterClassnameDefault_ = useOldOuterClassnameDefault_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.nestInFileClass_ = nestInFileClass_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.JavaFeaturesProto.JavaFeatures) {
          return mergeFrom((com.google.protobuf.JavaFeaturesProto.JavaFeatures)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.JavaFeaturesProto.JavaFeatures other) {
        if (other == com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDefaultInstance()) return this;
        if (other.hasLegacyClosedEnum()) {
          setLegacyClosedEnum(other.getLegacyClosedEnum());
        }
        if (other.hasUtf8Validation()) {
          setUtf8Validation(other.getUtf8Validation());
        }
        if (other.hasLargeEnum()) {
          setLargeEnum(other.getLargeEnum());
        }
        if (other.hasUseOldOuterClassnameDefault()) {
          setUseOldOuterClassnameDefault(other.getUseOldOuterClassnameDefault());
        }
        if (other.hasNestInFileClass()) {
          setNestInFileClass(other.getNestInFileClass());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                legacyClosedEnum_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                int tmpRaw = input.readEnum();
                com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation tmpValue =
                    com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  utf8Validation_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 24: {
                largeEnum_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                useOldOuterClassnameDefault_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                int tmpRaw = input.readEnum();
                com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass tmpValue =
                    com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(5, tmpRaw);
                } else {
                  nestInFileClass_ = tmpRaw;
                  bitField0_ |= 0x00000010;
                }
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean legacyClosedEnum_ ;
      /**
       * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the legacyClosedEnum field is set.
       */
      public boolean hasLegacyClosedEnum() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The legacyClosedEnum.
       */
      public boolean getLegacyClosedEnum() {
        return legacyClosedEnum_;
      }
      /**
       * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The legacyClosedEnum to set.
       * @return This builder for chaining.
       */
      public Builder setLegacyClosedEnum(boolean value) {

        legacyClosedEnum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool legacy_closed_enum = 1 [json_name = "legacyClosedEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearLegacyClosedEnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        legacyClosedEnum_ = false;
        onChanged();
        return this;
      }

      private int utf8Validation_ = 0;
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the utf8Validation field is set.
       */
      public boolean hasUtf8Validation() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The utf8Validation.
       */
      public com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation getUtf8Validation() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation result = com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.forNumber(utf8Validation_);
        return result == null ? com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation.UTF8_VALIDATION_UNKNOWN : result;
      }
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The utf8Validation to set.
       * @return This builder for chaining.
       */
      public Builder setUtf8Validation(com.google.protobuf.JavaFeaturesProto.JavaFeatures.Utf8Validation value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        utf8Validation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .pb.JavaFeatures.Utf8Validation utf8_validation = 2 [json_name = "utf8Validation", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FIELD, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearUtf8Validation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        utf8Validation_ = 0;
        onChanged();
        return this;
      }

      private boolean largeEnum_ ;
      /**
       * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the largeEnum field is set.
       */
      public boolean hasLargeEnum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The largeEnum.
       */
      public boolean getLargeEnum() {
        return largeEnum_;
      }
      /**
       * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The largeEnum to set.
       * @return This builder for chaining.
       */
      public Builder setLargeEnum(boolean value) {

        largeEnum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool large_enum = 3 [json_name = "largeEnum", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearLargeEnum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        largeEnum_ = false;
        onChanged();
        return this;
      }

      private boolean useOldOuterClassnameDefault_ ;
      /**
       * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return Whether the useOldOuterClassnameDefault field is set.
       */
      public boolean hasUseOldOuterClassnameDefault() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return The useOldOuterClassnameDefault.
       */
      public boolean getUseOldOuterClassnameDefault() {
        return useOldOuterClassnameDefault_;
      }
      /**
       * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @param value The useOldOuterClassnameDefault to set.
       * @return This builder for chaining.
       */
      public Builder setUseOldOuterClassnameDefault(boolean value) {

        useOldOuterClassnameDefault_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool use_old_outer_classname_default = 4 [json_name = "useOldOuterClassnameDefault", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_FILE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearUseOldOuterClassnameDefault() {
        bitField0_ = (bitField0_ & ~0x00000008);
        useOldOuterClassnameDefault_ = false;
        onChanged();
        return this;
      }

      private int nestInFileClass_ = 0;
      /**
       * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
       * @return Whether the nestInFileClass field is set.
       */
      public boolean hasNestInFileClass() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
       * @return The nestInFileClass.
       */
      public com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass getNestInFileClass() {
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass result = com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass.forNumber(nestInFileClass_);
        return result == null ? com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass.NEST_IN_FILE_CLASS_UNKNOWN : result;
      }
      /**
       * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
       * @param value The nestInFileClass to set.
       * @return This builder for chaining.
       */
      public Builder setNestInFileClass(com.google.protobuf.JavaFeaturesProto.JavaFeatures.NestInFileClassFeature.NestInFileClass value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000010;
        nestInFileClass_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .pb.JavaFeatures.NestInFileClassFeature.NestInFileClass nest_in_file_class = 5 [json_name = "nestInFileClass", retention = RETENTION_RUNTIME, targets = TARGET_TYPE_MESSAGE, targets = TARGET_TYPE_ENUM, targets = TARGET_TYPE_SERVICE, edition_defaults = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearNestInFileClass() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nestInFileClass_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.JavaFeatures)
    }

    // @@protoc_insertion_point(class_scope:pb.JavaFeatures)
    private static final com.google.protobuf.JavaFeaturesProto.JavaFeatures DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.JavaFeaturesProto.JavaFeatures();
    }

    public static com.google.protobuf.JavaFeaturesProto.JavaFeatures getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JavaFeatures>
        PARSER = new com.google.protobuf.AbstractParser<JavaFeatures>() {
      public JavaFeatures parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JavaFeatures> parser() {
      return PARSER;
    }

    public com.google.protobuf.Parser<JavaFeatures> getParserForType() {
      return PARSER;
    }

    public com.google.protobuf.JavaFeaturesProto.JavaFeatures getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int JAVA_FIELD_NUMBER = 1001;
  /**
   * <code>extend .google.protobuf.FeatureSet { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FeatureSet,
      com.google.protobuf.JavaFeaturesProto.JavaFeatures> java_ = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.class,
        com.google.protobuf.JavaFeaturesProto.JavaFeatures.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_JavaFeatures_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_JavaFeatures_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_JavaFeatures_NestInFileClassFeature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_JavaFeatures_NestInFileClassFeature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#google/protobuf/java_features.proto\022\002p" +
      "b\032 google/protobuf/descriptor.proto\"\337\010\n\014" +
      "JavaFeatures\022\220\002\n\022legacy_closed_enum\030\001 \001(" +
      "\010B\341\001\210\001\001\230\001\004\230\001\001\242\001\t\022\004true\030\204\007\242\001\n\022\005false\030\347\007\262\001" +
      "\273\001\010\350\007\020\350\007\032\262\001The legacy closed enum behavi" +
      "or in Java is deprecated and is schedule" +
      "d to be removed in edition 2025.  See ht" +
      "tp://protobuf.dev/programming-guides/enu" +
      "m/#java for more information.R\020legacyClo" +
      "sedEnum\022\257\002\n\017utf8_validation\030\002 \001(\0162\037.pb.J" +
      "avaFeatures.Utf8ValidationB\344\001\210\001\001\230\001\004\230\001\001\242\001" +
      "\014\022\007DEFAULT\030\204\007\262\001\310\001\010\350\007\020\351\007\032\277\001The Java-speci" +
      "fic utf8 validation feature is deprecate" +
      "d and is scheduled to be removed in edit" +
      "ion 2025.  Utf8 validation behavior shou" +
      "ld use the global cross-language utf8_va" +
      "lidation feature.R\016utf8Validation\022;\n\nlar" +
      "ge_enum\030\003 \001(\010B\034\210\001\001\230\001\006\230\001\001\242\001\n\022\005false\030\204\007\262\001\003" +
      "\010\351\007R\tlargeEnum\022n\n\037use_old_outer_classnam" +
      "e_default\030\004 \001(\010B(\210\001\001\230\001\001\242\001\t\022\004true\030\204\007\242\001\n\022\005" +
      "false\030\351\007\262\001\006\010\351\007 \351\007R\033useOldOuterClassnameD" +
      "efault\022\220\001\n\022nest_in_file_class\030\005 \001(\01627.pb" +
      ".JavaFeatures.NestInFileClassFeature.Nes" +
      "tInFileClassB*\210\001\001\230\001\003\230\001\006\230\001\010\242\001\013\022\006LEGACY\030\204\007" +
      "\242\001\007\022\002NO\030\351\007\262\001\003\010\351\007R\017nestInFileClass\032|\n\026Nes" +
      "tInFileClassFeature\"X\n\017NestInFileClass\022\036" +
      "\n\032NEST_IN_FILE_CLASS_UNKNOWN\020\000\022\006\n\002NO\020\001\022\007" +
      "\n\003YES\020\002\022\024\n\006LEGACY\020\003\032\010\"\006\010\351\007 \351\007J\010\010\001\020\200\200\200\200\002\"" +
      "F\n\016Utf8Validation\022\033\n\027UTF8_VALIDATION_UNK" +
      "NOWN\020\000\022\013\n\007DEFAULT\020\001\022\n\n\006VERIFY\020\002J\004\010\006\020\007:B\n" +
      "\004java\022\033.google.protobuf.FeatureSet\030\351\007 \001(" +
      "\0132\020.pb.JavaFeaturesR\004javaB(\n\023com.google." +
      "protobufB\021JavaFeaturesProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_pb_JavaFeatures_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_JavaFeatures_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_JavaFeatures_descriptor,
        new java.lang.String[] { "LegacyClosedEnum", "Utf8Validation", "LargeEnum", "UseOldOuterClassnameDefault", "NestInFileClass", });
    internal_static_pb_JavaFeatures_NestInFileClassFeature_descriptor =
      internal_static_pb_JavaFeatures_descriptor.getNestedTypes().get(0);
    internal_static_pb_JavaFeatures_NestInFileClassFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pb_JavaFeatures_NestInFileClassFeature_descriptor,
        new java.lang.String[] { });
    java_.internalInit(descriptor.getExtensions().get(0));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
